// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnwaj5rRp5gVx3nyQt2XkuZgrO4gMH04',
    appId: '1:87769904805:web:77834e0c5918e2e7ab7f4c',
    messagingSenderId: '87769904805',
    projectId: 'evently-26-pro',
    authDomain: 'evently-26-pro.firebaseapp.com',
    storageBucket: 'evently-26-pro.firebasestorage.app',
    measurementId: 'G-L9T8WE0ZFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjANFmNljzTNNHLhnFb8yQoPNzm8w_3fM',
    appId: '1:87769904805:android:b03f9b50e1240111ab7f4c',
    messagingSenderId: '87769904805',
    projectId: 'evently-26-pro',
    storageBucket: 'evently-26-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXvNjmyiCMRxeS75BSIDwONwXkRKZO2Q0',
    appId: '1:87769904805:ios:a5ee7765fe606a04ab7f4c',
    messagingSenderId: '87769904805',
    projectId: 'evently-26-pro',
    storageBucket: 'evently-26-pro.firebasestorage.app',
    iosBundleId: 'com.example.route',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXvNjmyiCMRxeS75BSIDwONwXkRKZO2Q0',
    appId: '1:87769904805:ios:a5ee7765fe606a04ab7f4c',
    messagingSenderId: '87769904805',
    projectId: 'evently-26-pro',
    storageBucket: 'evently-26-pro.firebasestorage.app',
    iosBundleId: 'com.example.route',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpnwaj5rRp5gVx3nyQt2XkuZgrO4gMH04',
    appId: '1:87769904805:web:19773e9542cb7c3fab7f4c',
    messagingSenderId: '87769904805',
    projectId: 'evently-26-pro',
    authDomain: 'evently-26-pro.firebaseapp.com',
    storageBucket: 'evently-26-pro.firebasestorage.app',
    measurementId: 'G-WTEFYPM64S',
  );
}
